site_name: Reproducible Research Tutorial
pages:
- Home: 'index.md'
- Pre-Requisites/Setup: 'setup/index.md'
- Hands-On 1 / (basic) Vagrant: 'hands-on-01.md'
- Hands-On 3 / Docker: '03-hands-on-docker.md'
- Documentation (RTFD): 'rtfd.md'
- Contributing:
  - 'Overview': 'contributing/index.md'
  - 'Directory Layout': 'contributing/layout.md'
  - 'Repository Setup and Developments': 'contributing/setup.md'
  - 'Semantic Versioning': 'contributing/versioning.md'
theme: readthedocs
